// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4o81_V55UE-7srvNjng8AgFHqKyRTvjs',
    appId: '1:95707773579:web:72d5f5efb5b5f9debbb28e',
    messagingSenderId: '95707773579',
    projectId: 'sufar-89113',
    authDomain: 'sufar-89113.firebaseapp.com',
    storageBucket: 'sufar-89113.firebasestorage.app',
    measurementId: 'G-FXELQCPMSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcQvr7BsLxqxU42tTFPyMNQ_T9BAo7EBI',
    appId: '1:95707773579:android:7a5070b8e607caf9bbb28e',
    messagingSenderId: '95707773579',
    projectId: 'sufar-89113',
    storageBucket: 'sufar-89113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi86HojY_zhQBNdOLoc9og-DCtIFeWcKs',
    appId: '1:95707773579:ios:ea1a9b3a4a55fb48bbb28e',
    messagingSenderId: '95707773579',
    projectId: 'sufar-89113',
    storageBucket: 'sufar-89113.firebasestorage.app',
    iosBundleId: 'com.example.sufarProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi86HojY_zhQBNdOLoc9og-DCtIFeWcKs',
    appId: '1:95707773579:ios:ea1a9b3a4a55fb48bbb28e',
    messagingSenderId: '95707773579',
    projectId: 'sufar-89113',
    storageBucket: 'sufar-89113.firebasestorage.app',
    iosBundleId: 'com.example.sufarProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4o81_V55UE-7srvNjng8AgFHqKyRTvjs',
    appId: '1:95707773579:web:2667d72feaea806dbbb28e',
    messagingSenderId: '95707773579',
    projectId: 'sufar-89113',
    authDomain: 'sufar-89113.firebaseapp.com',
    storageBucket: 'sufar-89113.firebasestorage.app',
    measurementId: 'G-DQGZL0XEQ3',
  );

}